import { test, expect } from '@playwright/test'
import { createRequire } from 'node:module'
const sharp: typeof import('sharp').default = createRequire(import.meta.url)('sharp')
test('collection search, metadata edits, hiding and removal',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/?demo=1');await expect(page.locator('.album-card')).toHaveCount(18)
 await page.getByRole('searchbox').fill('Soft Focus');await expect(page.locator('.album-card')).toHaveCount(1)
 await page.getByRole('button',{name:'Edit Soft Focus',exact:true}).click()
 await page.getByLabel('Album title').fill('New title')
 await page.getByLabel('Show on desktop',{exact:true}).uncheck()
 await page.getByRole('button',{name:'Save',exact:true}).click()
 await page.getByRole('searchbox').fill('New title');await expect(page.locator('.hidden-label')).toHaveText('Hidden')
 await page.getByRole('button',{name:'Edit New title'}).click();await page.getByRole('button',{name:'Remove album',exact:true}).click();await page.getByRole('button',{name:'Remove this album'}).click()
 await expect(page.getByRole('heading',{name:'No records found.'})).toBeVisible();expect(errors).toEqual([])
})
test('appearance updates preview and theme without errors',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 const spaces=page.getByRole('group',{name:'Spaces',exact:true});await expect(spaces.getByRole('button',{pressed:true})).toHaveText('All Spaces')
 await spaces.getByRole('button',{name:'This Space',exact:true}).click()
 await page.getByRole('button',{name:'Collection',exact:true}).click();await page.getByRole('button',{name:'Appearance',exact:true}).click()
 await expect(spaces.getByRole('button',{pressed:true})).toHaveText('This Space')
 await spaces.getByRole('button',{name:'All Spaces',exact:true}).click()
 const slider=page.getByRole('slider',{name:'Columns',exact:true});await slider.fill('8');await expect(page.locator('.preview-render .desktop-grid')).toHaveCSS('--columns','8')
 await expect(page.locator('.slider-field').filter({has:slider}).locator('output')).toHaveText('8')
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Light',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','light')
})
test('imports image, deduplicates, and reports invalid files',async({page})=>{
 await page.goto('/');await expect(page.getByRole('heading',{name:'Start with a record you love.'})).toBeVisible()
 const buffer=await sharp({create:{width:40,height:40,channels:3,background:'#a8b1c0'}}).png().toBuffer()
 const file={name:'Test Artist - Test Album.png',mimeType:'image/png',buffer}
 await page.getByLabel('Artwork files').setInputFiles(file);await expect(page.locator('.album-card')).toHaveCount(1)
 await page.getByLabel('Artwork files').setInputFiles(file);await expect(page.getByRole('status')).toContainText('already in your collection')
 await page.getByLabel('Artwork files').setInputFiles({name:'bad.png',mimeType:'image/png',buffer:Buffer.from('not an image')});await expect(page.getByRole('alert')).toContainText('bad.png')
})
test('desktop cover enlarges and returns to normal',async({page})=>{
 await page.goto('/?demo=1&desktop=1');const cover=page.locator('.desktop-cover').first();await cover.hover();await expect(cover).toHaveClass(/enlarged/)
 await expect(cover).toHaveCSS('cursor','pointer')
 await page.mouse.move(5,800);await expect(cover).not.toHaveClass(/enlarged/)
})

test('album editor closes on backdrop clicks but not clicks inside',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Edit Soft Focus',exact:true}).click()
 await expect(page.getByRole('dialog')).toBeVisible()
 const artwork=await page.locator('.editor-artwork').boundingBox(),close=await page.getByRole('button',{name:'Close album editor'}).boundingBox()
 expect(close!.y).toBeCloseTo(artwork!.y,0)
 await page.getByLabel('Album title').click();await expect(page.getByRole('dialog')).toBeVisible()
 await page.mouse.click(10,10);await expect(page.getByRole('dialog')).not.toBeVisible()
 await page.getByRole('button',{name:'Edit Soft Focus',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible()
 await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible()
})

test('preview preserves Mac and 4K aspect ratios and uses the selected layout',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 const preview=page.locator('.screen-preview');let r=await preview.boundingBox();expect(r!.width/r!.height).toBeCloseTo(1.6,1)
 await page.getByRole('button',{name:/4K monitor/}).click();r=await preview.boundingBox();expect(r!.width/r!.height).toBeCloseTo(16/9,1)
 await expect(page.getByRole('slider',{name:'Columns',exact:true})).toHaveValue('18')
})
test('replacing artwork retains album fields and updates both image variants',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Edit Soft Focus',exact:true}).click()
 const image=page.locator('.editor-artwork>img'),before=await image.getAttribute('src')
 await page.getByLabel('Replacement image').setInputFiles({name:'replacement.png',mimeType:'image/png',buffer:await sharp({create:{width:90,height:70,channels:3,background:'#c8724c'}}).png().toBuffer()})
 await expect(image).not.toHaveAttribute('src',before!);await expect(image).toHaveAttribute('src',/^data:image\/png/)
 await expect(page.getByLabel('Album title')).toHaveValue('Soft Focus');await expect(page.getByRole('button',{name:'Show original artwork in Finder'})).toBeVisible()
 await page.getByRole('button',{name:'Close album editor'}).click();await expect(page.getByRole('button',{name:'Edit Soft Focus',exact:true}).locator('img')).toHaveAttribute('src',/^data:image\/jpeg/)
})

test('quit modal supports cancel, backdrop dismissal and hide',async({page})=>{
 await page.goto('/?demo=1');await page.keyboard.press('Control+q');await expect(page.getByRole('dialog',{name:'Quit Plinth?'})).toBeVisible()
 await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible()
 await page.keyboard.press('Control+q');await page.mouse.click(5,5);await expect(page.getByRole('dialog')).not.toBeVisible()
 await page.keyboard.press('Control+q');await page.getByRole('button',{name:'Hide window',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible()
})

test('shuffle can be selected repeatedly and oldest date follows newest date',async({page})=>{
 await page.goto('/?demo=1');const titles=()=>page.locator('.album-title').allTextContents()
 await page.getByRole('button',{name:'Sort collection',exact:true}).click();await page.getByRole('menuitemradio',{name:'Shuffle',exact:true}).click();const first=await titles()
 await page.getByRole('button',{name:'Sort collection',exact:true}).click();await page.getByRole('menuitemradio',{name:'Shuffle',exact:true}).click();expect(await titles()).not.toEqual(first)
 await page.getByRole('button',{name:'Sort collection',exact:true}).click();await expect(page.getByRole('menuitemradio')).toHaveText(['Artist','Title','Newest date','Oldest date','Shuffle'])
 await page.getByRole('menuitemradio',{name:'Oldest date',exact:true}).click();await expect(page.getByRole('button',{name:'Sort collection',exact:true})).toHaveText('Oldest date')
})
test('daily shuffle appears only for Shuffle, keeps today\'s order, and reshuffles at midnight',async({page})=>{
 await page.clock.install({time:new Date(2026,9,2,23,58)});await page.goto('/?demo=1');const titles=()=>page.locator('.album-title').allTextContents();const daily=page.getByRole('checkbox',{name:'Daily',exact:true})
 await expect(daily).toHaveCount(0)
 await page.getByRole('button',{name:'Sort collection',exact:true}).click();await page.getByRole('menuitemradio',{name:'Shuffle',exact:true}).click();const shuffled=await titles()
 await daily.check();expect(await titles()).toEqual(shuffled)
 await page.clock.runFor(60000);expect(await titles()).toEqual(shuffled)
 await page.clock.runFor(120000);await expect.poll(titles).not.toEqual(shuffled);const tomorrow=await titles()
 await daily.uncheck();expect(await titles()).toEqual(tomorrow)
 await page.getByRole('button',{name:'Sort collection',exact:true}).click();await page.getByRole('menuitemradio',{name:'Artist',exact:true}).click();await expect(daily).toHaveCount(0)
})
test('collection toolbar controls share a centered row',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Sort collection',exact:true}).click();await page.getByRole('menuitemradio',{name:'Shuffle',exact:true}).click()
 const mids=await page.evaluate(()=>{const mid=(s:string)=>{const r=document.querySelector(s)!.getBoundingClientRect();return (r.top+r.bottom)/2};const header=document.querySelector('header')!.getBoundingClientRect().bottom,border=document.querySelector('.collection-toolbar')!.getBoundingClientRect().bottom;return {row:(header+border)/2,items:['.collection-meta','.search','.sort-trigger','.shuffle-daily'].map(mid)}})
 for(const mid of mids.items)expect(Math.abs(mid-mids.row)).toBeLessThanOrEqual(1)
})
test('Option page navigation wraps, desktop toggle uses action labels, internal artwork cannot drag',async({page})=>{
 await page.goto('/?demo=1');await expect(page.locator('.header-actions').getByRole('button')).toHaveText(['Disable','Add artworkCmd A']);await page.getByRole('button',{name:'Disable',exact:true}).click();await expect(page.locator('.header-actions').getByRole('button',{name:'Enable',exact:true})).toBeVisible()
 await page.keyboard.press('Alt+KeyQ');await expect(page.getByRole('group',{name:'App appearance'})).toBeVisible();await page.keyboard.press('Alt+KeyW');await expect(page.locator('.album-grid')).toBeVisible()
 const image=page.locator('.artwork img').first();await expect(image).toHaveAttribute('draggable','false')
 await page.getByRole('button',{name:'Edit Soft Focus',exact:true}).click();await expect(page.locator('.editor-artwork>img')).toHaveAttribute('draggable','false');await expect(page.locator('.artwork-actions')).toHaveCSS('opacity','0');await page.locator('.editor-artwork').hover();await expect(page.locator('.artwork-actions')).toHaveCSS('opacity','1')
})

test('quit modal has no default action, puts Hide window in the middle, and retains keyboard shortcuts',async({page})=>{
 await page.goto('/?demo=1')
 const dialog=page.getByRole('dialog',{name:'Quit Plinth?'})
 const show=async()=>{await page.keyboard.press('Control+q');await expect(dialog).toBeVisible();await expect(dialog.getByRole('heading')).toBeFocused()}
 await show()
 expect(await dialog.getByRole('button').evaluateAll(buttons=>buttons.map(button=>button.getAttribute('aria-label')))).toEqual(['Cancel','Hide window','Quit Plinth'])
 await expect(dialog.locator('button:focus')).toHaveCount(0)
 await expect(dialog.locator('button.primary')).toHaveCount(0)
 await page.keyboard.press('Enter');await expect(dialog).toBeVisible()
 await page.keyboard.press('Tab');await expect(dialog.getByRole('button',{name:'Cancel',exact:true})).toBeFocused()
 await page.keyboard.press('Enter');await expect(dialog).not.toBeVisible()
 await show();await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible()
 await show();await page.keyboard.press('Control+w');await expect(dialog).not.toBeVisible()
 await show();await page.keyboard.press('Control+q');await expect(dialog).not.toBeVisible()
 await show();await page.keyboard.press('/');await expect(dialog.getByRole('heading')).toBeFocused()
 await page.keyboard.press('Escape')
 await page.keyboard.down('Control');await page.keyboard.down('q');await page.keyboard.down('q');await expect(dialog).toBeVisible();await page.keyboard.up('q');await page.keyboard.up('Control')
})

test('desktop rows have equal margins, center incomplete rows, and cannot scroll',async({page})=>{
 for(const width of [1180,1550,2560]) {
  await page.setViewportSize({width,height:180})
  await page.goto('/?demo=1&desktop=1')
  await expect(page.locator('.desktop-cell')).toHaveCount(18)
  const rows=await page.locator('.desktop-cell').evaluateAll(cells=>{
   const rows:Record<string,{left:number;right:number;width:number}[]>={}
   for(const cell of cells){const r=cell.getBoundingClientRect();(rows[r.top]??=[]).push({left:r.left,right:r.right,width:r.width})}
   return Object.values(rows)
  })
  for(const row of rows){expect(Math.abs(row[0].left-(width-row.at(-1)!.right))).toBeLessThan(1);for(const cell of row)expect(cell.width).toBeCloseTo(rows[0][0].width,1)}
  const surface=page.locator('.desktop-surface')
  await expect(surface).toHaveCSS('overflow','clip')
  await page.mouse.move(width/2,100);await page.mouse.wheel(0,600)
  await page.keyboard.press('PageDown');await page.keyboard.press('End')
  await page.locator('.desktop-cover').last().evaluate(el=>el.focus())
  await page.evaluate(()=>window.scrollTo(0,600))
  await surface.evaluate(el=>el.scrollTo(0,600))
  expect(await surface.evaluate(el=>el.scrollTop)).toBe(0)
  expect(await page.evaluate(()=>window.scrollY)).toBe(0)
 }
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 await expect(page.getByRole('slider',{name:'Bottom scroll space'})).toHaveCount(0)
 await page.getByRole('slider',{name:'Columns',exact:true}).fill('7')
 const rows=await page.locator('.preview-render .desktop-cell').evaluateAll(cells=>{
  const rows:Record<string,DOMRect[]>={};for(const cell of cells){const r=cell.getBoundingClientRect();(rows[r.top]??=[]).push(r)}
  return Object.values(rows).map(row=>({center:(row[0].left+row.at(-1)!.right)/2,count:row.length}))
 })
 expect(rows.map(row=>row.count)).toEqual([7,7,4])
 for(const row of rows)expect(row.center).toBeCloseTo(rows[0].center,1)
})

test('Collection scrolls to every album with wheel, keyboard and focus, including after switching pages',async({page})=>{
 await page.setViewportSize({width:800,height:500})
 await page.goto('/?demo=1')
 await expect(page.locator('.album-card')).toHaveCount(18)
 const last=page.locator('.album-card .album-edit').last()
 await expect(last).not.toBeInViewport()
 await page.locator('.album-card').first().hover()
 await page.mouse.wheel(0,2400)
 await expect.poll(()=>page.evaluate(()=>window.scrollY)).toBeGreaterThan(0)
 await expect(last).toBeInViewport()
 await page.mouse.wheel(0,-2400)
 await expect.poll(()=>page.evaluate(()=>window.scrollY)).toBe(0)
 await page.keyboard.press('PageDown')
 await expect.poll(()=>page.evaluate(()=>window.scrollY)).toBeGreaterThan(0)
 await page.evaluate(()=>window.scrollTo(0,0))
 await last.evaluate(el=>el.focus())
 await expect(last).toBeInViewport()
 await last.press('Enter')
 await expect(page.getByRole('dialog')).toBeVisible()
 await page.getByRole('button',{name:'Close album editor'}).click()
 await page.getByRole('button',{name:'Appearance',exact:true}).click()
 await page.evaluate(()=>window.scrollTo(0,1200))
 await expect.poll(()=>page.evaluate(()=>window.scrollY)).toBeGreaterThan(0)
 await page.getByRole('button',{name:'Collection',exact:true}).click()
 await page.locator('.album-card').first().hover()
 await page.mouse.wheel(0,2400)
 await expect(last).toBeInViewport()
})

test('artwork gallery preserves editor changes and closes only the top modal',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Edit Soft Focus',exact:true}).click()
 await page.getByLabel('Album title').fill('Unsaved title')
 const artwork=page.locator('.editor-artwork'),viewer=page.getByRole('button',{name:'View original artwork',exact:true}),gallery=page.getByRole('dialog',{name:'Original artwork',exact:true})
 await expect(viewer).toHaveCSS('cursor','default')
 await artwork.hover()
 const bounds=(await artwork.boundingBox())!
 // The old controls captured this point, well above their visible icons.
 await page.mouse.click(bounds.x+bounds.width/4,bounds.y+bounds.height-65)
 await expect(gallery).toBeVisible()
 const image=gallery.locator('img')
 await expect(image).toHaveAttribute('src',(await artwork.locator('img').getAttribute('src'))!)
 await expect(image).toHaveAttribute('draggable','false')
 await expect(gallery).toHaveCSS('border-top-width','0px')
 await expect(gallery).toHaveCSS('cursor','default')
 const size=(await image.boundingBox())!
 expect(size.height).toBeCloseTo(852,0);expect(size.width).toBeCloseTo(size.height,0)
 await image.click();await expect(gallery).not.toBeVisible()
 await expect(page.locator('.album-dialog')).toBeVisible()
 await expect(page.getByLabel('Album title')).toHaveValue('Unsaved title')
 await viewer.click();await expect(gallery).toBeVisible()
 await page.mouse.click(5,5);await expect(gallery).not.toBeVisible()
 await expect(page.getByLabel('Album title')).toHaveValue('Unsaved title')
 await expect(viewer).toBeFocused()
 await page.keyboard.press('Space');await expect(gallery).toBeVisible()
 await page.keyboard.press('Escape');await expect(gallery).not.toBeVisible()
 await expect(page.locator('.album-dialog')).toBeVisible()
 await expect(page.getByLabel('Album title')).toHaveValue('Unsaved title')
 const chooser=page.waitForEvent('filechooser')
 await page.getByRole('button',{name:'Replace artwork',exact:true}).click();await chooser
 await expect(gallery).not.toBeVisible()
 await expect(page.getByRole('button',{name:'Show original artwork in Finder',exact:true})).toBeDisabled()
 await expect(gallery).not.toBeVisible()
 await page.keyboard.press('Escape');await expect(page.locator('.album-dialog')).not.toBeVisible()
})

test('gallery fits landscape and portrait originals without distortion',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Edit Soft Focus',exact:true}).click()
 for(const [width,height] of [[160,80],[80,160]]){
  await page.getByLabel('Replacement image').setInputFiles({name:'aspect.png',mimeType:'image/png',buffer:await sharp({create:{width,height,channels:3,background:'#c8724c'}}).png().toBuffer()})
  await expect(page.locator('.editor-artwork')).not.toHaveClass(/replacing/)
  await page.getByRole('button',{name:'View original artwork',exact:true}).click()
  const image=page.locator('.artwork-gallery img')
  await expect.poll(async()=>{const box=(await image.boundingBox())!;return box.width/box.height}).toBeCloseTo(width/height,2)
  const box=(await image.boundingBox())!
  expect(box.width).toBeLessThanOrEqual(1132);expect(box.height).toBeLessThanOrEqual(852)
  expect(Math.max(box.width/1132,box.height/852)).toBeCloseTo(1,2)
  await page.keyboard.press('Escape')
 }
})
