import { test, expect } from '@playwright/test'
import { createRequire } from 'node:module'
const sharp:typeof import('sharp').default=createRequire(import.meta.url)('sharp')
const historyPage=async(page:import('@playwright/test').Page)=>{if(!await page.locator('.settings-dialog').isVisible())await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'History',exact:true}).click();await expect(page.locator('.history-list')).toBeVisible()}

test('History opens from Settings and saves full metadata states',async({page})=>{
 await page.goto('/?demo=1')
 await expect(page.getByRole('navigation',{name:'Main navigation'}).getByRole('button').locator(':scope > span')).toHaveText(['Collection','Appearance','Stats'])
 await historyPage(page)
 await expect(page.locator('.history-list>li')).toHaveCount(1)
 await expect(page.getByRole('button',{name:'Undo',exact:true})).toBeDisabled()
 await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeDisabled()
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'Collection',exact:true}).click()
 await page.getByRole('button',{name:'Edit Soft Focus',exact:true}).click()
 await page.getByLabel('Album title').fill('Soft Focus Remastered')
 await page.getByLabel('Artist',{exact:true}).fill('Mira Vale Ensemble')
 await page.getByLabel('Show on desktop',{exact:true}).uncheck()
 await page.keyboard.press('Escape')
 await historyPage(page)
 await expect(page.locator('.history-list>li')).toHaveCount(2)
 await page.locator('.history-list summary').click()
 await expect(page.locator('.history-list')).toContainText('Title: Soft Focus → Soft Focus Remastered')
 await expect(page.locator('.history-list')).toContainText('Artist: Mira Vale → Mira Vale Ensemble')
 await page.getByRole('button',{name:'Undo',exact:true}).click()
 await expect(page.locator('.history-list>li.current')).toContainText('Starting state')
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'Collection',exact:true}).click()
 await expect(page.getByRole('button',{name:'Edit Soft Focus',exact:true})).toBeVisible()
 await page.keyboard.press('Meta+Shift+z')
 await expect(page.getByRole('button',{name:'Edit Soft Focus Remastered',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Edit Soft Focus Remastered',exact:true}).click()
 await expect(page.getByLabel('Artist',{exact:true})).toHaveValue('Mira Vale Ensemble')
 await expect(page.getByLabel('Show on desktop',{exact:true})).not.toBeChecked()
})

test('undo flushes pending appearance changes and restores the preview and desktop toggle',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 const columns=page.getByRole('slider',{name:'Columns',exact:true})
 const original=await columns.inputValue()
 await columns.fill('7');await columns.focus();await page.keyboard.press('Meta+z')
 await expect(columns).toHaveValue(original)
 await expect(page.locator('.preview-render .desktop-grid')).toHaveCSS('--columns',original)
 await page.keyboard.press('Meta+Shift+z');await expect(columns).toHaveValue('7')
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'Collection',exact:true}).click()
 await page.getByRole('button',{name:'Disable',exact:true}).click()
 await page.keyboard.press('Meta+z')
 await expect(page.getByRole('button',{name:'Disable',exact:true})).toBeVisible()
 await historyPage(page);await expect(page.locator('.history-list>li')).toHaveCount(3)
 await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled()
})

test('new changes after undo retain abandoned states and Restore returns to either branch',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Settings',exact:true}).click()
 await page.getByRole('button',{name:'Light',exact:true}).click();await historyPage(page)
 await page.getByRole('button',{name:'Back to Settings',exact:true}).click();await page.getByRole('button',{name:'Logo 3',exact:true}).click();await historyPage(page)
 await page.getByRole('button',{name:'Undo',exact:true}).click()
 await page.getByRole('button',{name:'Back to Settings',exact:true}).click();await page.getByRole('button',{name:'System',exact:true}).click();await historyPage(page)
 await expect(page.locator('.history-list>li')).toHaveCount(4)
 await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeDisabled()
 await expect(page.locator('.history-list>li.current')).toContainText('From state 2')
 await page.getByRole('button',{name:'Restore state 3',exact:true}).click()
 await expect(page.locator('html')).toHaveAttribute('data-theme','light')
 await expect(page.locator('.brand image')).toHaveAttribute('href','/logos/logo-3.png')
 await page.getByRole('button',{name:'Restore state 1',exact:true}).click()
 await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
 await page.getByRole('button',{name:'Restore state 2',exact:true}).click()
 await expect(page.locator('html')).toHaveAttribute('data-theme','light')
 await page.getByRole('button',{name:'Redo',exact:true}).click()
 await expect(page.locator('.brand image')).toHaveAttribute('href','/logos/logo-3.png')
 await expect(page.locator('.history-list>li')).toHaveCount(4)
})

test('undo restores removed albums and both artwork variants',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Edit Soft Focus',exact:true}).click()
 const old=await page.locator('.editor-artwork>img').getAttribute('src')
 await page.getByLabel('Replacement image').setInputFiles({name:'Synthetic replacement.png',mimeType:'image/png',buffer:await sharp({create:{width:80,height:90,channels:3,background:'#6c8075'}}).png().toBuffer()})
 await expect(page.locator('.editor-artwork>img')).not.toHaveAttribute('src',old!)
 await page.getByRole('button',{name:'Remove album',exact:true}).click();await page.getByRole('dialog',{name:'Remove “Soft Focus”?'}).getByRole('button',{name:'Remove album',exact:true}).click()
 await expect(page.locator('.album-card')).toHaveCount(17)
 await page.keyboard.press('Meta+z');await expect(page.locator('.album-card')).toHaveCount(18)
 await page.getByRole('button',{name:'Edit Soft Focus',exact:true}).click()
 await expect(page.locator('.editor-artwork>img')).toHaveAttribute('src',/^data:image\/png/)
 await page.keyboard.press('Escape');await page.keyboard.press('Meta+z')
 await page.getByRole('button',{name:'Edit Soft Focus',exact:true}).click()
 await expect(page.locator('.editor-artwork>img')).toHaveAttribute('src',old!)
})

test('imports are one state per batch and duplicates and no-op saves do not add history',async({page})=>{
 await page.goto('/')
 const buffer=await sharp({create:{width:40,height:40,channels:3,background:'#8a645a'}}).png().toBuffer()
 const file={name:'Synthetic Artist - New Album.png',mimeType:'image/png',buffer}
 await page.getByLabel('Artwork files').setInputFiles(file);await expect(page.locator('.album-card')).toHaveCount(1)
 await page.getByLabel('Artwork files').setInputFiles(file)
 await page.getByRole('button',{name:'Edit New Album',exact:true}).click();await page.getByLabel('Artist',{exact:true}).fill('Synthetic Artist');await page.keyboard.press('Escape')
 await historyPage(page);await expect(page.locator('.history-list>li')).toHaveCount(2)
 await page.getByRole('button',{name:'Undo',exact:true}).click()
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'Collection',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Start with a record you love.'})).toBeVisible()
 await page.keyboard.press('Meta+Shift+z');await expect(page.locator('.album-card')).toHaveCount(1)
})

test('text undo and modal shortcuts do not navigate saved history',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Disable',exact:true}).click()
 const search=page.getByRole('searchbox');await search.focus();await page.keyboard.type('Soft Focus');await page.keyboard.press('Meta+z')
 await expect(search).not.toHaveValue('Soft Focus')
 await search.fill('Soft Focus')
 await expect(page.getByRole('button',{name:'Enable',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Edit Soft Focus',exact:true}).click();await page.keyboard.press('Meta+z')
 await expect(page.locator('.album-dialog')).toBeVisible()
 await page.keyboard.press('Escape');await historyPage(page)
 await expect(page.locator('.history-list>li')).toHaveCount(2)
 await expect(page.getByRole('navigation').getByRole('button',{name:'Collection',exact:true})).toHaveAttribute('aria-current','page');await page.getByRole('button',{name:'Back to Settings',exact:true}).click();await expect(page.getByRole('group',{name:'App appearance'})).toBeVisible()
 await historyPage(page);await page.keyboard.press('Alt+KeyQ');await expect(page.locator('.history-list')).toBeVisible();await page.keyboard.press('Escape');await page.keyboard.press('Alt+KeyQ');await expect(page.locator('.stats-page')).toBeVisible()
})


test('all history entries remain reachable in a narrow window',async({page})=>{
 await page.setViewportSize({width:640,height:500})
 await page.goto('/?demo=1')
 for(let index=0;index<8;index++){
  if(await page.locator('.settings-dialog').isVisible())await page.getByRole('button',{name:'Back to Settings',exact:true}).click();else await page.getByRole('button',{name:'Settings',exact:true}).click()
  await page.getByRole('button',{name:index%2===0?'Light':'Dark',exact:true}).click()
  await historyPage(page)
 }
 await expect(page.locator('.history-list>li')).toHaveCount(9)
 const baseline=page.getByRole('button',{name:'Restore state 1',exact:true})
 await baseline.scrollIntoViewIfNeeded();await expect(baseline).toBeInViewport()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
 await baseline.click();await expect(page.locator('.history-list>li.current')).toContainText('Starting state')
 await expect(page.locator('.history-list>li')).toHaveCount(9)
})
