import {test,expect} from '@playwright/test'
test('holding Hover size previews one album, follows dragging, and ends on release outside',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 const slider=page.getByRole('slider',{name:'Hover size',exact:true})
 await slider.scrollIntoViewIfNeeded()
 const r=(await slider.boundingBox())!
 await page.mouse.move(r.x+r.width*.6,r.y+r.height/2);await page.mouse.down()
 const sample=page.locator('.preview-render .desktop-cover.enlarged')
 await expect(sample).toHaveCount(1)
 const name=await sample.getAttribute('aria-label')
 await page.mouse.move(r.x+r.width*.9,r.y+r.height/2,{steps:5})
 await expect(sample).toHaveAttribute('aria-label',name!)
 const value=Number(await slider.inputValue())
 await expect.poll(()=>sample.evaluate(el=>Number(getComputedStyle(el).transform.split('(')[1].split(',')[0]))).toBeCloseTo(value,1)
 await page.mouse.move(5,5);await page.mouse.up()
 await expect(page.locator('.preview-render .desktop-cover.enlarged')).toHaveCount(0)
})
test('right-click does not preview; cancellation and blur clear the sample',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 const slider=page.getByRole('slider',{name:'Hover size',exact:true})
 await slider.scrollIntoViewIfNeeded();const r=(await slider.boundingBox())!
 await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down({button:'right'})
 await expect(page.locator('.desktop-cover.enlarged')).toHaveCount(0)
 await page.mouse.up({button:'right'});await page.keyboard.press('Escape')
 await page.mouse.down();await expect(page.locator('.desktop-cover.enlarged')).toHaveCount(1)
 await slider.dispatchEvent('pointercancel');await expect(page.locator('.desktop-cover.enlarged')).toHaveCount(0)
 await page.mouse.up();await page.mouse.down();await expect(page.locator('.desktop-cover.enlarged')).toHaveCount(1)
 await page.evaluate(()=>window.dispatchEvent(new Event('blur')))
 await expect(page.locator('.desktop-cover.enlarged')).toHaveCount(0);await page.mouse.up()
})
test('hover-size sample works with hover disabled and an empty library is harmless',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 await page.getByRole('checkbox',{name:/Enlarge on hover/}).uncheck()
 const slider=page.getByRole('slider',{name:'Hover size',exact:true})
 await slider.scrollIntoViewIfNeeded();let r=(await slider.boundingBox())!
 await page.mouse.move(r.x+r.width*.75,r.y+r.height/2);await page.mouse.down()
 await expect(page.locator('.desktop-cover.enlarged')).toHaveCount(1);await page.mouse.up()
 await expect(page.locator('.desktop-cover.enlarged')).toHaveCount(0)
 await page.goto('/');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 await slider.scrollIntoViewIfNeeded();r=(await slider.boundingBox())!
 await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down()
 await expect(page.locator('.desktop-cover.enlarged')).toHaveCount(0);await page.mouse.up()
})

test('hover speed is saved in history and corners animate with scale',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 const speed=page.getByRole('slider',{name:'Hover speed',exact:true})
 await speed.fill('0.25')
 await page.getByRole('slider',{name:'Rounded corners',exact:true}).fill('20')
 await page.mouse.move(0,0)
 await page.waitForTimeout(1100)
 await page.clock.install()
 const cover=page.locator('.preview-render .desktop-cover').first()
 await cover.hover()
 await page.clock.runFor(500)
 const middle=await cover.evaluate(el=>({radius:parseFloat(getComputedStyle(el).borderRadius),scale:Number(getComputedStyle(el).transform.split('(')[1].split(',')[0])}))
 expect(middle.radius).toBeGreaterThan(3);expect(middle.radius).toBeLessThan(17)
 expect(middle.scale).toBeGreaterThan(1.2);expect(middle.scale).toBeLessThan(1.9)
 await page.clock.runFor(600);await expect(cover).toHaveCSS('border-radius','0px')
 await page.mouse.move(0,0);await page.clock.runFor(500)
 const returning=await cover.evaluate(el=>parseFloat(getComputedStyle(el).borderRadius))
 expect(returning).toBeGreaterThan(3);expect(returning).toBeLessThan(17)
 await page.clock.runFor(600);await expect(cover).toHaveCSS('border-radius','20px')
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'History',exact:true}).click()
 await expect(page.locator('.history-list')).toContainText('Hover speed: 1 → 0.25')
})


test('background hover option sits beneath enlarge and restores through history',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 const enlarge=page.getByRole('checkbox',{name:'Enlarge on hover',exact:true})
 const background=page.getByRole('checkbox',{name:'While another app has focus',exact:true})
 await expect(background).toBeChecked()
 await expect(page.locator('.toggle-row').filter({has:enlarge}).locator('+ .toggle-row')).toContainText('While another app has focus')
 await background.uncheck()
 await page.keyboard.press('Meta+z');await expect(background).toBeChecked()
 await page.keyboard.press('Meta+Shift+z');await expect(background).not.toBeChecked()
 await enlarge.uncheck();await expect(background).toBeDisabled()
 await enlarge.check();await expect(background).toBeEnabled();await expect(background).not.toBeChecked()
})

test('rounded corners on hover default off and restore independently for each display',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 const toggle=page.getByRole('checkbox',{name:'When hovered',exact:true})
 await expect(toggle).not.toBeChecked()
 await page.getByRole('slider',{name:'Rounded corners',exact:true}).fill('20')
 await toggle.check()
 const cover=page.locator('.preview-render .desktop-cover').first()
 await cover.hover()
 await expect(cover).toHaveClass(/enlarged/)
 await expect(cover).toHaveCSS('border-radius','20px')
 await page.mouse.move(0,0)
 await page.keyboard.press('Meta+z');await expect(toggle).not.toBeChecked()
 await cover.hover();await expect(cover).toHaveCSS('border-radius','0px')
 await page.mouse.move(0,0)
 await page.keyboard.press('Meta+Shift+z');await expect(toggle).toBeChecked()
 await cover.hover();await expect(cover).toHaveCSS('border-radius','20px')
 await page.getByRole('button',{name:/4K monitor/}).click()
 await expect(toggle).not.toBeChecked()
 await page.getByRole('button',{name:/Mac display/}).click()
 await expect(toggle).toBeChecked()
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'History',exact:true}).click()
 await expect(page.locator('.history-list')).toContainText('Rounded corners when hovered: Off → On')
})
