import {test,expect} from '@playwright/test'
test('holding Hover size previews one album, follows dragging, and ends on release outside',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 const slider=page.getByRole('slider',{name:'Hover size',exact:true})
 await slider.scrollIntoViewIfNeeded()
 const r=(await slider.boundingBox())!
 await page.mouse.move(r.x+r.width*.6,r.y+r.height/2);await page.mouse.down()
 const sample=page.locator('.preview-render .desktop-cover.enlarged')
 await expect(sample).toHaveCount(1)
 const name=await sample.getAttribute('aria-label')
 await page.mouse.move(r.x+r.width*.9,r.y+r.height/2,{steps:5})
 await expect(sample).toHaveAttribute('aria-label',name!)
 const value=Number(await slider.inputValue())
 await expect.poll(()=>sample.evaluate(el=>el.getBoundingClientRect().width/el.parentElement!.getBoundingClientRect().width)).toBeCloseTo(value,1)
 await page.mouse.move(5,5);await page.mouse.up()
 await expect(page.locator('.preview-render .desktop-cover.enlarged')).toHaveCount(0)
})
test('hover sliders retain native pointer dragging',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 for(const name of ['Hover size','Hover speed']){
  const slider=page.getByRole('slider',{name,exact:true})
  await slider.scrollIntoViewIfNeeded()
  const r=(await slider.boundingBox())!
  await page.mouse.move(r.x+r.width*.25,r.y+r.height/2);await page.mouse.down()
  await page.mouse.move(r.x+r.width*.75,r.y+r.height/2,{steps:5});await page.mouse.up()
  expect(Number(await slider.inputValue())).toBeGreaterThan(Number(await slider.getAttribute('min'))+(Number(await slider.getAttribute('max'))-Number(await slider.getAttribute('min')))*.6)
 }
})
test('right-click does not preview; cancellation and blur clear the sample',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 const slider=page.getByRole('slider',{name:'Hover size',exact:true})
 await slider.scrollIntoViewIfNeeded();const r=(await slider.boundingBox())!
 await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down({button:'right'})
 await expect(page.locator('.desktop-cover.enlarged')).toHaveCount(0)
 await page.mouse.up({button:'right'});await page.keyboard.press('Escape')
 await page.mouse.down();await expect(page.locator('.desktop-cover.enlarged')).toHaveCount(1)
 await slider.dispatchEvent('pointercancel');await expect(page.locator('.desktop-cover.enlarged')).toHaveCount(0)
 await page.mouse.up();await page.mouse.down();await expect(page.locator('.desktop-cover.enlarged')).toHaveCount(1)
 await page.evaluate(()=>window.dispatchEvent(new Event('blur')))
 await expect(page.locator('.desktop-cover.enlarged')).toHaveCount(0);await page.mouse.up()
})
test('hover-size sample works with hover disabled and an empty library is harmless',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 await page.getByRole('checkbox',{name:/Enlarge on hover/}).uncheck()
 const slider=page.getByRole('slider',{name:'Hover size',exact:true})
 await slider.scrollIntoViewIfNeeded();let r=(await slider.boundingBox())!
 await page.mouse.move(r.x+r.width*.75,r.y+r.height/2);await page.mouse.down()
 await expect(page.locator('.desktop-cover.enlarged')).toHaveCount(1);await page.mouse.up()
 await expect(page.locator('.desktop-cover.enlarged')).toHaveCount(0)
 await page.goto('/');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 await slider.scrollIntoViewIfNeeded();r=(await slider.boundingBox())!
 await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down()
 await expect(page.locator('.desktop-cover.enlarged')).toHaveCount(0);await page.mouse.up()
})

test('hover speed is saved in history and corners animate with scale',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 const speed=page.getByRole('slider',{name:'Hover speed',exact:true})
 await expect(speed).toHaveValue('250')
 await expect(speed).toHaveAttribute('aria-valuetext','250 milliseconds')
 await speed.fill('1000')
 await expect(speed.locator('..').locator('output')).toHaveText('1000 ms')
 await page.getByRole('slider',{name:'Rounded corners',exact:true}).fill('20')
 await page.mouse.move(0,0)
 await page.waitForTimeout(1100)
 await page.clock.install()
 const cover=page.locator('.preview-render .desktop-cover').first()
 await cover.hover()
 await page.clock.runFor(500)
 const middle=await cover.evaluate(el=>({radius:parseFloat(getComputedStyle(el).borderRadius),scale:el.getBoundingClientRect().width/el.parentElement!.getBoundingClientRect().width}))
 expect(middle.radius).toBeGreaterThan(3);expect(middle.radius).toBeLessThan(17)
 expect(middle.scale).toBeGreaterThan(1.2);expect(middle.scale).toBeLessThan(1.9)
 await page.clock.runFor(600);await expect(cover).toHaveCSS('border-radius','0px')
 await page.mouse.move(0,0);await page.clock.runFor(500)
 const returning=await cover.evaluate(el=>parseFloat(getComputedStyle(el).borderRadius))
 expect(returning).toBeGreaterThan(3);expect(returning).toBeLessThan(17)
 await page.clock.runFor(600);await expect(cover).toHaveCSS('border-radius','20px')
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'History',exact:true}).click()
 await expect(page.locator('.history-list')).toContainText('Hover speed: 250 ms → 1000 ms')
})


test('background hover option sits beneath enlarge and restores through history',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 const enlarge=page.getByRole('checkbox',{name:'Enlarge on hover',exact:true})
 const background=page.getByRole('checkbox',{name:'While another app has focus',exact:true})
 await expect(background).toBeChecked()
 await expect(page.locator('.toggle-row').filter({has:enlarge}).locator('+ .toggle-row')).toContainText('While another app has focus')
 await background.uncheck()
 await page.keyboard.press('Meta+z');await expect(background).toBeChecked()
 await page.keyboard.press('Meta+Shift+z');await expect(background).not.toBeChecked()
 await enlarge.uncheck();await expect(background).toBeDisabled()
 await enlarge.check();await expect(background).toBeEnabled();await expect(background).not.toBeChecked()
})

test('rounded corners on hover default off and restore independently for each display',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 const toggle=page.getByRole('checkbox',{name:'When hovered',exact:true})
 await expect(toggle).not.toBeChecked()
 await page.getByRole('slider',{name:'Rounded corners',exact:true}).fill('20')
 await toggle.check()
 const cover=page.locator('.preview-render .desktop-cover').first()
 await cover.hover()
 await expect(cover).toHaveClass(/enlarged/)
 await expect(cover).toHaveCSS('border-radius','20px')
 await page.mouse.move(0,0)
 await page.keyboard.press('Meta+z');await expect(toggle).not.toBeChecked()
 await cover.hover();await expect(cover).toHaveCSS('border-radius','0px')
 await page.mouse.move(0,0)
 await page.keyboard.press('Meta+Shift+z');await expect(toggle).toBeChecked()
 await cover.hover();await expect(cover).toHaveCSS('border-radius','20px')
 await page.getByRole('button',{name:/4K monitor/}).click()
 await expect(toggle).not.toBeChecked()
 await page.getByRole('button',{name:/Mac display/}).click()
 await expect(toggle).toBeChecked()
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'History',exact:true}).click()
 await expect(page.locator('.history-list')).toContainText('Rounded corners when hovered: Off → On')
})

test('hovering pushes nearby artwork away, less with distance, and the toggle restores through history',async({page})=>{
 await page.goto('/?demo=1');await page.getByRole('button',{name:'Appearance',exact:true}).click()
 await page.getByRole('button',{name:/Mac display/}).click();await page.getByRole('slider',{name:'Columns',exact:true}).fill('6')
 const cells=page.locator('.preview-render .desktop-cell')
 const offset=(i:number)=>cells.nth(i).evaluate(el=>{const m=new DOMMatrix(getComputedStyle(el).transform);return {x:m.m41,y:m.m42}})
 await cells.nth(3).scrollIntoViewIfNeeded();await cells.nth(3).hover()
 await expect.poll(async()=>(await offset(4)).x).toBeGreaterThan(5)
 await page.waitForTimeout(400)
 const [left,right,farther,below,far]=await Promise.all([2,4,5,9,17].map(offset))
 expect(left.x).toBeLessThan(-5);expect(right.x).toBeGreaterThan(farther.x);expect(farther.x).toBeGreaterThan(0)
 expect(below.y).toBeGreaterThan(5);expect(far).toEqual({x:0,y:0})
 expect(await offset(3)).toEqual({x:0,y:0})
 await page.mouse.move(0,0)
 await expect.poll(()=>cells.nth(4).evaluate(el=>el.style.transform+el.style.willChange)).toBe('')
 const toggle=page.getByRole('checkbox',{name:'Push nearby artwork',exact:true})
 await expect(toggle).toBeChecked();await toggle.uncheck()
 await cells.nth(3).hover();await page.waitForTimeout(400)
 expect(await offset(4)).toEqual({x:0,y:0})
 await page.getByRole('checkbox',{name:'Enlarge on hover',exact:true}).uncheck();await expect(toggle).toBeDisabled()
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'History',exact:true}).click()
 await expect(page.locator('.history-list')).toContainText('Push nearby artwork: On → Off')
})

test('desktop hit areas meet across gaps so one album is always enlarged, and enlargement stays unscaled',async({page})=>{
 await page.setViewportSize({width:1512,height:982})
 await page.goto('/?desktop=1&demo=1')
 const cells=page.locator('.desktop-cell');await expect(cells).toHaveCount(18)
 const rects=await cells.evaluateAll(els=>els.map(el=>{const r=el.getBoundingClientRect();return {id:el.getAttribute('data-id'),left:r.left,top:r.top,right:r.right,bottom:r.bottom}}))
 const [a,b]=rects;const lastRow=rects.filter(r=>r.top>a.top)
 expect(lastRow.length).toBeGreaterThan(0)
 const enlarged=page.locator('.desktop-cover.enlarged')
 // Column gap: each side of its midpoint belongs to the closer cover.
 for(const [x,id] of [[a.right+(b.left-a.right)*.25,a.id],[a.right+(b.left-a.right)*.75,b.id]] as const){
  await page.mouse.move(x,a.top+20);await expect(enlarged).toHaveCount(1);await expect(enlarged.locator('..')).toHaveAttribute('data-id',id!)
 }
 // Row gap and the empty space beside a centered last row still enlarge the nearest album.
 const gapY=(a.bottom+lastRow[0].top)/2
 for(const [x,y] of [[a.left+5,gapY],[rects.at(-1)!.right+30,lastRow[0].top+10],[a.left+5,lastRow[0].bottom-5]]){
  await page.mouse.move(x,y);await expect(enlarged).toHaveCount(1)
 }
 await page.mouse.move(a.left+5,a.bottom+5);await expect(enlarged.locator('..')).toHaveAttribute('data-id',a.id!)
 await page.mouse.move(a.left+5,lastRow[0].top-5);await expect(enlarged.locator('..')).not.toHaveAttribute('data-id',a.id!)
 // Outside the artwork's extent nothing is hovered.
 await page.mouse.move(1510,980);await expect(enlarged).toHaveCount(0)
 await page.mouse.move((b.left+b.right)/2,(b.top+b.bottom)/2)
 const cover=cells.nth(1).locator('.desktop-cover')
 await expect.poll(()=>cover.evaluate(el=>el.getBoundingClientRect().width/el.parentElement!.getBoundingClientRect().width)).toBeCloseTo(2.1,2)
 await expect(cover).toHaveCSS('transform','none')
})
