import { test, expect } from '@playwright/test'
import { createRequire } from 'node:module'
const sharp: typeof import('sharp').default = createRequire(import.meta.url)('sharp')
import { mkdir } from 'node:fs/promises'
test('README screenshots use only synthetic demo artwork',async({page})=>{
 await page.setViewportSize({width:1550,height:840})
 await page.goto('/?demo=1');await expect(page.locator('.album-card')).toHaveCount(18)
 await page.evaluate(async()=>{await Promise.all(Array.from(document.images).map(i=>i.decode()))})
 await mkdir('docs/screenshots',{recursive:true})
 await page.mouse.move(0,0)
 await sharp(await page.screenshot({fullPage:true,animations:'disabled'})).webp({quality:86}).toFile('docs/screenshots/collection.webp')
 await page.getByRole('button',{name:'Appearance',exact:true}).click()
 await page.getByRole('button',{name:/4K monitor/}).click()
 await page.evaluate(()=>{Math.random=()=>.5})
 const hoverSlider=page.getByRole('slider',{name:'Hover size',exact:true})
 const hoverBounds=(await hoverSlider.boundingBox())!
 await page.mouse.move(hoverBounds.x+hoverBounds.width*.55,hoverBounds.y+hoverBounds.height/2)
 await page.mouse.down()
 await expect(page.locator('.preview-render .desktop-cover.enlarged')).toHaveCount(1)
 await page.waitForTimeout(300)
 await sharp(await page.screenshot({fullPage:true,animations:'disabled'})).webp({quality:86}).toFile('docs/screenshots/appearance.webp')
 await page.mouse.up()
 await page.getByRole('button',{name:'Settings',exact:true}).click()
 await page.mouse.move(0,0)
 await sharp(await page.screenshot({fullPage:true,animations:'disabled'})).webp({quality:86}).toFile('docs/screenshots/settings.webp')
 await page.getByRole('button',{name:'Collection',exact:true}).click()
 await page.getByRole('button',{name:'Edit Soft Focus',exact:true}).click()
 await page.locator('.editor-artwork').hover()
 await sharp(await page.locator('.album-dialog').screenshot({animations:'disabled'})).webp({quality:86}).toFile('docs/screenshots/album.webp')
 await page.getByRole('button',{name:'Close album editor'}).click()
 await page.keyboard.press('Control+q')
 await sharp(await page.getByRole('dialog',{name:'Quit Plinth?'}).screenshot()).webp({quality:86}).toFile('docs/screenshots/quit.webp')
})
