import { test, expect } from '@playwright/test'
import { createRequire } from 'node:module'
const sharp: typeof import('sharp').default = createRequire(import.meta.url)('sharp')
import { mkdir } from 'node:fs/promises'
test('README screenshots use only synthetic demo artwork',async({page})=>{
 await page.addInitScript(()=>{Date.now=()=>Date.UTC(2026,8,10,17,0)})
 await page.setViewportSize({width:1550,height:840})
 await page.goto('/?demo=1');await expect(page.locator('.album-card')).toHaveCount(18)
 await page.evaluate(async()=>{await Promise.all(Array.from(document.images).map(i=>i.decode()))})
 await mkdir('docs/screenshots',{recursive:true})
 await page.getByRole('button',{name:'View Soft Focus artwork',exact:true}).hover()
 await expect(page.getByRole('button',{name:'View Soft Focus artwork',exact:true})).toHaveCSS('opacity','1')
 await sharp(await page.screenshot({fullPage:true,animations:'disabled'})).webp({quality:86}).toFile('docs/screenshots/collection.webp')
 await page.getByRole('button',{name:'Appearance',exact:true}).click()
 await page.getByRole('button',{name:/4K monitor/}).click()
 await page.evaluate(()=>{Math.random=()=>.5})
 const hoverSlider=page.getByRole('slider',{name:'Hover size',exact:true})
 const hoverBounds=(await hoverSlider.boundingBox())!
 await page.mouse.move(hoverBounds.x+hoverBounds.width*.55,hoverBounds.y+hoverBounds.height/2)
 await page.mouse.down()
 await expect(page.locator('.preview-render .desktop-cover.enlarged')).toHaveCount(1)
 await page.waitForTimeout(300)
 await sharp(await page.screenshot({fullPage:true,animations:'disabled'})).webp({quality:86}).toFile('docs/screenshots/appearance.webp')
 await page.mouse.up()
 await page.getByRole('button',{name:'Settings',exact:true}).click()
 await page.mouse.move(0,0)
 await sharp(await page.screenshot({fullPage:true,animations:'disabled'})).webp({quality:86}).toFile('docs/screenshots/settings.webp')
 await page.getByRole('button',{name:'Collection',exact:true}).click()
 await page.getByRole('button',{name:'Edit Soft Focus',exact:true}).click()
 await page.locator('.editor-artwork').hover()
 await sharp(await page.locator('.album-dialog').screenshot({animations:'disabled'})).webp({quality:86}).toFile('docs/screenshots/album.webp')
 await page.getByRole('button',{name:'View original artwork',exact:true}).click()
 await page.locator('.artwork-gallery img').evaluate(async(image:HTMLImageElement)=>image.decode())
 await page.mouse.move(0,0)
 await sharp(await page.screenshot({animations:'disabled'})).webp({quality:86}).toFile('docs/screenshots/gallery.webp')
 await page.keyboard.press('Escape')
 await page.getByRole('button',{name:'Close album editor'}).click()
 await page.keyboard.press('Control+q')
 await sharp(await page.getByRole('dialog',{name:'Quit Plinth?'}).screenshot()).webp({quality:86}).toFile('docs/screenshots/quit.webp')
 await page.keyboard.press('Escape')
 await page.evaluate(()=>{Date.now=()=>Date.UTC(2026,8,10,17,12)})
 await page.getByRole('button',{name:'Edit Soft Focus',exact:true}).click()
 await page.getByLabel('Album title').fill('Soft Focus — Remastered')
 await page.getByLabel('Release date').fill('2026-09-01')
 await page.getByRole('button',{name:'Save',exact:true}).click()
 await page.evaluate(()=>{Date.now=()=>Date.UTC(2026,8,10,17,18)})
 await page.getByRole('button',{name:'Disable',exact:true}).click()
 await page.getByRole('button',{name:'History',exact:true}).click()
 await expect(page.locator('.history-list>li')).toHaveCount(3)
 await page.locator('.history-list summary').click()
 await page.mouse.move(0,0)
 await expect(page.locator('.toast')).not.toBeVisible({timeout:8000})
 await sharp(await page.screenshot({fullPage:true,animations:'disabled'})).webp({quality:86}).toFile('docs/screenshots/history.webp')
})
